import { OrganizationUnit, PublicService, UserProfile } from '../../types';
import { getJobLevel } from '../identity/identity';
const normalize = (value: string) => value.toLowerCase().replace(/[^a-z0-9]/g, '');
const CODE_TO_UNIT: Record<string, string> = {'LYN-001':'Bidang Perencanaan Makro','LYN-002':'Bidang Litbang & Inovasi','LYN-003':'Bidang Litbang & Inovasi','LYN-004':'Bidang Litbang & Inovasi','LYN-005':'DOMAIN_DEPENDENT','LYN-006':'Bidang Perencanaan Makro','LYN-007':'DOMAIN_DEPENDENT','LYN-008':'DOMAIN_DEPENDENT','LYN-009':'Bidang Litbang & Inovasi'};
const aliases: Record<string,string[]> = {'sekretariat':['sekretariat','sekretariatbadan'],'bidang perencanaan makro':['makro','perencanaanmakro','bidmakro'],'bidang perencanaan ekonomi':['ekonomi','perencanaanekonomi','bidekonomi'],'bidang perencanaan sosbud':['sosbud','perencanaansosbud','bidsosbud'],'bidang perencanaan fispra':['fispra','perencanaanfispra','bidfispra'],'bidang litbang & inovasi':['litbang','penelitiandanpengembangan','inovasi','bidlitbang']};
function unitMatches(userUnit:string, expected:string){const u=normalize(userUnit),e=normalize(expected);return u===e||(aliases[expected]||[]).map(normalize).includes(u);}
export function resolveServiceUnit(service:Pick<PublicService,'code'|'unitInCharge'>,org:OrganizationUnit[]=[]){const mapped=CODE_TO_UNIT[service.code];const wanted=mapped&&mapped!=='DOMAIN_DEPENDENT'?mapped:service.unitInCharge;const match=org.find(unit=>unitMatches(unit.name,wanted)||normalize(unit.id)===normalize(wanted));return match?.id||wanted;}
export function routePublicService(service:Pick<PublicService,'code'|'unitInCharge'>,users:UserProfile[],org:OrganizationUnit[]=[]){const mapped=CODE_TO_UNIT[service.code];const expected=mapped&&mapped!=='DOMAIN_DEPENDENT'?mapped:service.unitInCharge;return users.filter(user=>{const level=getJobLevel(user);if(level==='SUPERADMIN'||level==='FRONTOFFICE')return false;return unitMatches(user.unit,expected)||unitMatches(user.unit,service.unitInCharge);});}
export function canProcessService(user:UserProfile,service:PublicService){const level=getJobLevel(user);if(level==='SUPERADMIN')return true;if(!['KABID','STAF','KASUBAG'].includes(level))return false;return routePublicService(service,[user]).some(candidate=>candidate.id===user.id);}
